### PR TITLE
various improvements and cleanups

### PR DESCRIPTION
**Pull request by tarsius**
Please refer to the commit messages.

### CODE REVIEW

**Comment by sabof** [comment]
Thanks, looks mostly good. Isn't the `turn-on-X-mode` convention "old school"?

**Comment by tarsius** [comment]
Is it? I didn't know. What would be the new way of doing that?

**Comment by sabof** [comment]
I assumed all current conventions where handled by the define-minor-mode macro. Plus I wasn't aware of it. Seems harmless, so I might as well keep it.

Btw, I took the review as an opportunity for a re-write - it should be faster, and there will no longer be any need for stripe-max-buffer-size.

**Comment by sabof** [comment]
I've created a new branch, https://github.com/sabof/stripe-buffer/tree/smart_redraw. You can test-drive it if you wish.

**Comment by tarsius** [comment]
The version in `smart_redraw` is indeed much faster, I like it.

**Pull request merged**
